-- create & insert tabel users
create table users (
id int8 not null generated by default as identity,
username varchar(255) null,
email_address varchar(255) null,
"password" varchar(255) null,
constraint pkey_users primary key (id)
);

insert into public.users
(username, email_address, "password") values
('anies56', 'anies56@gmail.com', '456789'),
('rasyid23', 'rasyid23@gmail.com', '123456'),
('baswedan89', 'baswedan89@gmail.com', '654321');

-- create & insert tabel merchant
create table merchant (
id int8 not null generated by default as identity,
merchant_name varchar(255) null,
merchant_location varchar(255) null,
"open" boolean null,
constraint pkey_merchant primary key (id)
);

insert into public.merchant
(merchant_name, merchant_location, "open") values
('Toko Jaya', 'Semarang', true),
('SuperMart', 'Bali', false),
('Kedai Serba Ada', 'Kupang', true);

-- create & insert tabel Order
create table "Order" (
id int8 not null generated by default as identity,
order_time timestamp null,
destination_address varchar(255) null,
user_id int8 null,
completed boolean null,
constraint pkey_Order primary key (id),
constraint const_user_id foreign key (user_id) references users(id)
);

insert into public."Order"
(order_time, destination_address, user_id, completed) values
(now(), 'Rawasari', 1, true),
(now(), 'Cideng', 1, false),
(now(), 'Kampung Rawa', 2, true),
(now(), 'Kemayoran', 2, false),
(now(), 'Gondangdia', 3, true),
(now(), 'Kwitang', 3, false);

-- create & insert tabel product
create table product (
id int8 not null generated by default as identity,
product_name varchar(255) null,
price int8 null,
merchant_id int8 null,
constraint pkey_product primary key (id),
constraint const_merchant_id foreign key (merchant_id) references merchant(id)
);

insert into public.product 
(product_name, price, merchant_id) values
('Beras', 25000, 1),
('Telur Ayam', 8000, 1),
('Minyak Goreng', 15000, 2),
('Susu Sapi', 10000, 2),
('Daging Ayam Paha', 30000, 3),
('Pasta Gigi', 25000, 3);

-- create & insert table order detail
create table orderdetail (
id int8 not null generated by default as identity,
order_id int8 null,
product_id int8 null,
quantity int8 null,
total_price int8 null,
constraint pkey_orderdetail primary key (id),
constraint const_order_id foreign key (order_id) references "Order"(id),
constraint const_product_id foreign key (product_id) references product(id)
);

insert into public.orderdetail
(order_id, product_id, quantity, total_price) values
(1, 3, 4, 28000),
(1, 5, 6, 39000),
(2, 2, 5, 25000),
(2, 1, 8, 47000),
(3, 6, 3, 15000),
(3, 1, 6, 31000),
(4, 4, 7, 37000),
(4, 3, 5, 23000),
(5, 5, 4, 34000),
(5, 6, 3, 17000);